# use_logoå¦‚æœä¸ºtrue, éœ€è¦åœ¨logo_imageè®¾ç½®è·¯å¾„
use_logo: false
logo_image:  # ä½¿ç”¨è·¯å¾„, å¡«å†™æ–‡ä»¶åå³å¯(æ¯”å¦‚, logo_image: logo.png æŒ‡å‘ source/imgs/logo.png)
navbar_text: # å¦‚æœæ²¡æœ‰Logo, åˆ™è®¾ç½®ä¸ºfalse, å¹¶ä¸”è®¾ç½®navbar_text(å¦åˆ™é»˜è®¤ä¸ºç«™ç‚¹æ ‡é¢˜, æœ€å¥½è¿›è¡Œè®¾ç½®)

# å¿…å¡«, è®¾å®šå°å‹è®¾å¤‡å±•ç¤ºèƒŒæ™¯å›¾, æŒ‡å‘source/imgs, æ¯”å¦‚xs_bg_image: bg.png -> source/imgs/bg.png
xs_bg_image: xsbg.gif

# å¿…å¡«, ä¸ªäººå¤´åƒ, å¦‚æœæ˜¯è·¯å¾„, åˆ™æŒ‡å‘source/imgs
# ä¹Ÿå¯ä»¥å¡«http:// OR https:// urlåœ°å€
author_image: https://avatars1.githubusercontent.com/u/32896990?s=460&v=4

# å¯¼èˆªèœå•
menu:
  # index
  - title: é¦–é¡µ
    # å‚ç…§font-awesomeå®˜ç½‘çš„icon, å–åé¢ä¸€æ®µ(æ¯”å¦‚ç”¨fa-starè¿™ä¸ªå›¾æ ‡, é‚£ä¹ˆè¿™é‡Œçš„iconå°±å¡«star)
    icon: home
    url: /
  # archives
  - title: å½’æ¡£
    icon: archive
    url: archives
  # categories
  - title: åˆ†ç±»
    icon: list
    url: categories
    dropdown: 3 #dropdownä¸ºä¸‹æ‹‰èœå•å‡ºç°çš„é¡¹ç›®æœ€å¤§æ•°ç›®(åªé™äºtagså’Œcategorys)
    # å¦‚æœä¸æƒ³æ˜¾ç¤ºä¸‹æ‹‰èœå•, åˆ™ä¸è¦å¡«å†™, å³dropdown:
    # å…·ä½“æ•ˆæœå¯ä»¥çœ‹https://myau.moe
  # tags
  - title: æ ‡ç­¾
    icon: tags
    url: tags
    dropdown: 3
  # about, è¿™ä¸ªå®é™…ä¸Šæ˜¯è‡ªå®šä¹‰page, åé¢çš„è‡ªå®šä¹‰pageå‚ç…§aboutæ ·å¼
  - title: å…³äºæˆ‘
    icon: user
    url: about

# æ¯ç¯‡æ–‡ç« çš„previewé»˜è®¤å›¾ç‰‡
# å¿…å¡«é¡¹(é™¤éä½ æ¯ç¯‡æ–‡ç« çš„front-matteréƒ½è®¾ç½®äº†previewå±æ€§)
# å¡«å†™: å¯ä»¥æ”¾å¤šå¼ å›¾, å°†éšæœºæŠ½å–ä½œä¸ºé»˜è®¤çš„previewå›¾ç‰‡
# å¦‚æœä½¿ç”¨æ–‡ä»¶ååˆ™å¯¹åº”ç›®å½•: source/imgs/preview, æ¯”å¦‚ preview1.jpg -> source/imgs/preview/preview1.jpg
# å¦‚æœç”¨urlåˆ™å¡«å†™å®Œæ•´çš„urlåœ°å€å³å¯
default_preview:
  - preview1.jpg
  - preview2.jpg
  - preview3.jpg
  - preview4.jpg

# ä¾§è¾¹æ 
sidebar:
  recent_comments: true   # æœ€æ–°è¯„è®º, é»˜è®¤å…³é—­, å¯èƒ½éœ€è¦è‡ªå·±è¿›è¡Œæ¨¡æ¿é…ç½®
  hot_posts: true         # æœ€çƒ­æ–‡ç« , å¦‚æœé…ç½®äº†ä¸‹é¢çš„æ–‡ç« ç»Ÿè®¡å°±å¯ä»¥ä½¿ç”¨è¯¥ä¾§è¾¹æ , å¦åˆ™è®¾ç½®ä¸ºfalse
  recent_posts: true      # æœ€æ–°æ–‡ç« , é»˜è®¤å¼€å¯
  random_posts: true      # éšæœºæ–‡ç« , é»˜è®¤å¼€å¯
  tags: true              # çƒ­é—¨æ ‡ç­¾, é»˜è®¤å¼€å¯
  friend_links: true      # å‹æƒ…é“¾æ¥, é»˜è®¤å¼€å¯
  links: true             # ä¸ªäººé“¾æ¥, é»˜è®¤å¼€å¯

# å‹æƒ…é“¾æ¥é…ç½®, è¦å…ˆå¼€å¯ä¸Šé¢çš„friend_links
friend_links:
  - name: æ©™å­ğŸŠ
    link: https://czorange123.github.io/
  - name: sdu
    link: https://meditator.cc/
  - name: KDays Forum
    link: http://kdays.net/days/
  - name: ç»…å£«å¯¼èˆªâ™‚
    link: http://www.gal123.com/
  - name: èŒå¯¼èˆª
    link: http://www.moe123.com/

# ä¸ªäººé“¾æ¥é…ç½®, è¦å…ˆå¼€å¯ä¸Šé¢çš„links
links:
  - name: æ–°æµª
    link: https://weibo.com/p/1005055487978197/home?from=page_100505&mod=TAB#place
  - name: è±†ç“£
    link: https://www.douban.com/people/164032129/


# æ˜¯å¦ä½¿ç”¨å…¬å‘Š
# å…¬å‘Šæ˜¯ä»€ä¹ˆå¯ä»¥çœ‹https://myau.moe
# å¦‚æœä½¿ç”¨äº†å…¬å‘Š, é‚£ä¹ˆå…¬å‘Šå†…å®¹éœ€è¦è‡ªå·±å»é…ç½®
# åœ¨ä¸»é¢˜ä¸‹çš„layout/_partial/issue.ejsè¿›è¡Œå†…å®¹ä¿®æ”¹
# å¦‚æœä¸ç”¨å…¬å‘Š, è¯·è®¾ç½®æ­¤é¡¹ä¸ºfalse
use_issue: true

# èƒŒæ™¯å›¾åŠŸèƒ½
# å¿…å¡«é¡¹
slide_background:
  # é»˜è®¤ä¸ºfalse, å³é‡‡ç”¨è·¯å¾„å›¾ç‰‡
  use_url: false
  # use_url: trueæƒ…å†µä¸‹, é‡‡ç”¨ä¸ƒç‰›å¤–é“¾ç©ºé—´çš„å½¢å¼, ä¸‹é¢ä¸‰ä¸ªå‚æ•°ç»„åˆæŒ‡å‘: http://ouo1ro65u.bkt.clouddn.com/background(1~10).png
  # prefix: http://ouo1ro65u.bkt.clouddn.com/background   ä¸ƒç‰›å¯¹è±¡å­˜å‚¨ç©ºé—´å¤–é“¾ä¸»æœºåœ°å€å’Œå›¾ç‰‡åç§°å‰ç¼€
  # ext: png          å›¾ç‰‡çš„åç¼€æ ¼å¼, è¦æ±‚å¯ä¾›é€‰æ‹©çš„å›¾ç‰‡éƒ½æ˜¯ç»Ÿä¸€åç¼€
  # max_count: 10     å¯ä¾›é€‰æ‹©çš„å›¾ç‰‡æ•°é‡, èƒŒæ™¯å›¾ä¼šä»è¿™é‡ŒéšæœºæŠ½å–6å¼ å›¾

  # use_url: falseæƒ…å†µä¸‹, é‡‡ç”¨æœ¬åœ°åšå®¢å›¾ç‰‡è·¯å¾„, ä¸‹é¢ä¸‰ä¸ªå‚æ•°ç»„åˆæŒ‡å‘: source/imgs/slide/background(1~10).jpg
  prefix: slide/background
  ext: jpg
  mac_count: 6


# æ˜¯å¦å¼€å¯æ¬§å°¼é…±åŠŸèƒ½
open_oni: true
# æ¬§å°¼é…±åŠŸèƒ½è®¾ç½®, å‰æä¸ºopen_oni: true
oni_setting:
  # é™ä¸‰é¡¹, å¯ä»¥è‡ªå·±é…ç½®é“¾æ¥(ä¸€èˆ¬æ˜¯ä¸Šé¢çš„menuæˆ–è€…è‡ªå·±çš„page)
  - title: å½’æ¡£
    url: archives
  - title: å…³äº
    url: about
  - title: ç•™è¨€æ¿
    url: message
# æ¬§å°¼é…±é€‰é¡¹å›¾ç‰‡(å¯ä»¥è‡ªå·±æ›¿æ¢, æœ€å¥½æ˜¯100 * 100åƒç´ çš„å›¾ç‰‡)
# å›¾ç‰‡ä¸ºé»˜è®¤çš„ source/imgs/oni/oni(1~6).jpg
# å¦‚æœè‡ªå·±æ›¿æ¢äº†ä¸åŒåç¼€çš„å›¾ç‰‡, éœ€è¦åœ¨ source/css/_common.cssä¸­ä¿®æ”¹(ç›´æ¥ctrl + Fæœoni)


# è¾“å…¥ç‰¹æ•ˆactivate-power-mode
# https://github.com/disjukr/activate-power-mode
power_mode:
  colorful: true
  shake: true

# æ–‡ç« ç»Ÿè®¡, ç›®å‰åªæ”¯æŒleancloud(å¯èƒ½åˆ°æ—¶æ·»åŠ ä¸è’œå­ç»Ÿè®¡)
# è·å–appIdå’ŒappKeyæ–¹æ³•ç›´æ¥ç™¾åº¦ or google(æˆ–è€…çœ‹è¿™ç¯‡http://crescentmoon.info/2014/12/11/popular-widget/)
# æ³¨æ„ä¸€æ—¦ç”Ÿæˆæ–°çš„æ–‡ç« å°±ä¸è¦éšä¾¿æ”¹åäº†
leancloud:
  appid:  # your appId
  appkey: # your appKey

# è¯„è®ºç³»ç»Ÿ, ç›®å‰åªæ”¯æŒgitment(ä¸ºäº†è‡ªå®šä¹‰æ ·å¼)
# å…³äºgitmentå¦‚ä½•é…ç½®çœ‹è¿™ç¯‡ https://imsun.net/posts/gitment-introduction/
# å¦‚æœä¸ç”¨çš„è¯è¦æŠŠä¸‹é¢çš„use_commentè®¾ç½®ä¸ºfalse
comment:
  gitment:
      owner: 32896990 # å¿…å¡«é¡¹, ä½ çš„GitHub ID
      repo: git@github.com:YuAngBoy/comment.git # å¿…å¡«é¡¹  ä½ çš„å­˜å‚¨è¯„è®ºçš„repo
      oauth:
        client_id: c91c6bd31e68da7dc2f0 # å¿…å¡«é¡¹
        client_secret: 1cc3db655fb0b82c72afad16c590409ceef83a7c # å¿…å¡«é¡¹
        redirect_uri: # å¯ä»¥å¡«ä¹Ÿå¯ä»¥ä¸å¡«

# livere: #æ–°å¢ æ¥æ¯”åŠ›è¯„è®ºï¼Œæ²¡æœ‰æ•ˆæœ
#   enable: true #æ–°å¢ï¼Œæ§åˆ¶è¯„è®ºæ˜¾ç¤º
#   livere_uid: MTAyMC8zNTA1My8xMTU4OA

# æ˜¯å¦ä½¿ç”¨è¯„è®ºç³»ç»Ÿ
use_comment: false

node_sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false